services:
  barracuda-vision:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda-vision
    privileged: true
    tty: true
    network_mode: host
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $XAUTHORITY:/root/.Xauthority:ro
    environment:
      - DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]