services:
  barracuda-vision:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda-vision
    privileged: true
    tty: true
    network_mode: host
    volumes:
      - $HOME/.ssh:/root/.ssh
      - ${XAUTHORITY:-/tmp/.Xauthority}:/root/.Xauthority:ro
      - ${MODEL_PATH:-/localmodels}:/opt/barracuda-vision/catkin_ws/src/barracuda_vision/localModels
    environment:
      - DISPLAY
      - XAUTHORITY=${XAUTHORITY:-/tmp/.Xauthority}